name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  check-rust:
    name: Rust Checks & Tests
    runs-on: ubuntu-latest

    steps:
      - uses: actions/actions@v4

      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@stable
        with:
          components: clippy, dependencies

      - name: Install Tauri dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libgtk-3-dev libwebkit2gtk-4.1-dev libappindicator3-dev librsvg2-dev patchelf

      - name: Cache cargo dependencies
        uses: Swatinem/rust-cache@v2
        with:
          workspaces: src-tauri

      - name: Check Formatting
        run: cargo fmt --manifest-path src-tauri/Cargo.toml --check

      - name: Clippy linter
        run: cargo clippy --manifest-path src-tauri/Cargo.toml -- -D warnings

      - name: Run Tests
        run: cargo test --manifest-path src-tauri/Cargo.toml
